apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: jorgeaceval/calculadora:1.3
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_USER
              value: user
            - name: RABBITMQ_PASS
              value: pass
          command: ["python", "consumer.py"]
